name: Build & Deploy Docs

on:
  push:
    branches:
        - '**'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: '14.x'
        cache: 'npm'
        cache-dependency-path: package-lock.json
    - run: npm install
    - run: npm install typedoc
    - run: npx typedoc index.ts
    - name: deploy to github pages
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
          branch: gh-pages
          folder: docs